ebook_metadata:
  title: ༄༅༅། །ཚོགས་གསོག་མཆོད་འབུལ་སྣ་ཚོགས་ཀྱི་སྐོར་ཚོགས་གཉིས་ནོར་བུ་རྒྱས་པའི་སྤྲིན་ཆེན་རྒྱལ་བའི་རྟེན་གསུམ་བཞེངས་པ་དང་མཆོད་པའི་ཕན་ཡོན་ལས་འཕྲོས་པའི་གཏམ་བཅས།
    །
  authors:
  - མཛད་པ་པོ། ཞེ་ཆེན་རྒྱལ་ཚབ་འགྱུར་མེད་པདྨ་རྣམ་རྒྱལ།
  sku: SHE-SG-01
  layers:
  - book_title
  - author
  - chapter_title
  - quotation
  - sabche
  - yigchung
web_metadata:
  title:
    en: Miscellaneous Writings
    bo: ཚོགས་གསོག་མཆོད་འབུལ་གྱི་སྐོར།༼ཀ༽
  collection:
    en: Shechen Gyaltsab Series–  Book 1
    bo: ཞེ་ཆེན་རྒྱལ་ཚབ་གསུང་འབུམ།–  དེབ། ༡
  author:
    en: Shechen Gyaltsap Gyurme Pema Namgyal
    bo: ཞེ་ཆེན་རྒྱལ་ཚབ་འགྱུར་མེད་པདྨ་རྣམ་རྒྱལ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-SG-01
  category:
    en: Uncategorized
    bo: སྡེ་ཚན་མེད་པ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-SG-01.epub
  description:
    en: ''
    bo: ''
